{"uuid":"60c03dc2-42be-462f-ab7f-38cae8e1ba5d","historyId":"e3a191651869da56ca0bafe452ccdfcd","testCaseId":"[engine:junit-jupiter]/[class:ru.apatch.addressbook.tests.GroupModificationTests]/[method:canModifyGroup()]","testCaseName":"canModifyGroup()","fullName":"ru.apatch.addressbook.tests.GroupModificationTests.canModifyGroup","labels":[{"name":"junit.platform.uniqueid","value":"[engine:junit-jupiter]/[class:ru.apatch.addressbook.tests.GroupModificationTests]/[method:canModifyGroup()]"},{"name":"host","value":"DESKTOP-VFD5C7B"},{"name":"thread","value":"5132@DESKTOP-VFD5C7B.Test worker(1)"},{"name":"framework","value":"junit-platform"},{"name":"language","value":"java"},{"name":"package","value":"ru.apatch.addressbook.tests.GroupModificationTests"},{"name":"testClass","value":"ru.apatch.addressbook.tests.GroupModificationTests"},{"name":"testMethod","value":"canModifyGroup"},{"name":"suite","value":"ru.apatch.addressbook.tests.GroupModificationTests"}],"links":[],"name":"canModifyGroup()","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Error calling DriverManager#getConnection [null]","trace":"org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Error calling DriverManager#getConnection [null]\r\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:276)\r\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)\r\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)\r\n\tat org.hibernate.boot.model.relational.Database.<init>(Database.java:45)\r\n\tat org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:230)\r\n\tat org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:198)\r\n\tat org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:166)\r\n\tat org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:125)\r\n\tat org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:451)\r\n\tat org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:102)\r\n\tat org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:910)\r\n\tat org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:960)\r\n\tat ru.apatch.addressbook.manager.HibernateHelper.<init>(HibernateHelper.java:28)\r\n\tat ru.apatch.addressbook.manager.ApplicationManager.hbm(ApplicationManager.java:84)\r\n\tat ru.apatch.addressbook.tests.GroupModificationTests.canModifyGroup(GroupModificationTests.java:16)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tSuppressed: java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\t\tat ru.apatch.addressbook.manager.JdbcHelper.checkConsistency(JdbcHelper.java:61)\r\n\t\tat ru.apatch.addressbook.tests.TestBase.checkDatabaseConsistency(TestBase.java:28)\r\n\t\t... 3 more\r\n\tCaused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\t\tat com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165)\r\n\t\tat com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:837)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:420)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:238)\r\n\t\tat com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180)\r\n\t\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)\r\n\t\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)\r\n\t\tat ru.apatch.addressbook.manager.JdbcHelper.checkConsistency(JdbcHelper.java:53)\r\n\t\t... 4 more\r\n\tCaused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\t\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)\r\n\t\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)\r\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)\r\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95)\r\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140)\r\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156)\r\n\t\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:79)\r\n\t\tat com.mysql.cj.NativeSession.connect(NativeSession.java:142)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:961)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)\r\n\t\t... 10 more\r\n\tCaused by: java.net.ConnectException: Connection refused: connect\r\n\t\tat java.base/sun.nio.ch.Net.connect0(Native Method)\r\n\t\tat java.base/sun.nio.ch.Net.connect(Net.java:589)\r\n\t\tat java.base/sun.nio.ch.Net.connect(Net.java:578)\r\n\t\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)\r\n\t\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)\r\n\t\tat java.base/java.net.Socket.connect(Socket.java:751)\r\n\t\tat com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:144)\r\n\t\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:53)\r\n\t\t... 13 more\r\nCaused by: org.hibernate.exception.JDBCConnectionException: Error calling DriverManager#getConnection [null]\r\n\tat org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:100)\r\n\tat org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator$1.convert(BasicConnectionCreator.java:107)\r\n\tat org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.convertSqlException(BasicConnectionCreator.java:132)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionCreator.makeConnection(DriverManagerConnectionCreator.java:39)\r\n\tat org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:61)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.addConnections(DriverManagerConnectionProviderImpl.java:497)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.<init>(DriverManagerConnectionProviderImpl.java:363)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections$Builder.build(DriverManagerConnectionProviderImpl.java:548)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.buildPool(DriverManagerConnectionProviderImpl.java:101)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:81)\r\n\tat org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:135)\r\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)\r\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)\r\n\tat org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:354)\r\n\tat org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:236)\r\n\tat org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:82)\r\n\tat org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:43)\r\n\tat org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:129)\r\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)\r\n\t... 17 more\r\nCaused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\tat com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165)\r\n\tat com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:837)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:420)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:238)\r\n\tat com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180)\r\n\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)\r\n\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:191)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionCreator.makeConnection(DriverManagerConnectionCreator.java:36)\r\n\t... 32 more\r\nCaused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\tat java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)\r\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)\r\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)\r\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)\r\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95)\r\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140)\r\n\tat com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156)\r\n\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:79)\r\n\tat com.mysql.cj.NativeSession.connect(NativeSession.java:142)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:961)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)\r\n\t... 38 more\r\nCaused by: java.net.ConnectException: Connection refused: connect\r\n\tat java.base/sun.nio.ch.Net.connect0(Native Method)\r\n\tat java.base/sun.nio.ch.Net.connect(Net.java:589)\r\n\tat java.base/sun.nio.ch.Net.connect(Net.java:578)\r\n\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)\r\n\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)\r\n\tat java.base/java.net.Socket.connect(Socket.java:751)\r\n\tat com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:144)\r\n\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:53)\r\n\t... 41 more\r\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1745841564560,"stop":1745841564579}